-- Migration catalogue v14 : posters manquants + posters événementiels + md_sofa (test staff)
-- Rejouable sans doublon (INSERT IGNORE sur l'id). Rollback : *_down.sql. Généré 2026-10-09 20:39
-- NB: catalogue_pages.id n'est pas auto-increment -> ids explicites (stables sur cette base et ses restaurations).

-- 1) Pages créées
INSERT IGNORE INTO catalogue_pages (id,order_id,min_role,index_visible,is_club_only,name_index,link_list,name,layout,image_headline,image_teasers,body,label_pick,label_extra_s,label_extra_t) VALUES ('214','207','1','1','0','Événementiels','','Posters événementiels','ctlg_layout2','','','Posters spéciaux d''événements et de promotions.','Clique sur le meuble voulu',NULL,NULL);
INSERT IGNORE INTO catalogue_pages (id,order_id,min_role,index_visible,is_club_only,name_index,link_list,name,layout,image_headline,image_teasers,body,label_pick,label_extra_s,label_extra_t) VALUES ('215','999','5','1','0','TEST','','TEST (staff)','ctlg_layout2','','','Page de test réservée au staff — ne pas rendre publique.','Clique sur le meuble voulu',NULL,NULL);

-- 2) Définition md_sofa
INSERT IGNORE INTO items_definitions (id,sprite,sprite_id,name,description,colour,length,width,top_height,max_status,behaviour,interactor,is_tradable,is_recyclable,drink_ids) VALUES ('2267','md_sofa','12135','Canapé','Canapé de la gamme Bubble Juice.','','2','1','1','1','can_sit_on_top','','1','1','');

-- 3) Offres (21 posters + canapé md_sofa)
INSERT IGNORE INTO catalogue_items (id,sale_code,page_id,order_id,price,is_hidden,amount,definition_id,item_specialspriteid,name,description,is_package,package_name,package_description) VALUES ('2266','poster 56','24','36','3','0','1','251','56','Panneau Disco','Fais la fête sur tes murs !','0',NULL,NULL);
INSERT IGNORE INTO catalogue_items (id,sale_code,page_id,order_id,price,is_hidden,amount,definition_id,item_specialspriteid,name,description,is_package,package_name,package_description) VALUES ('2267','poster 21','24','37','3','0','1','251','21','Vitrine à papillons','Magnifique reproduction de papillon','0',NULL,NULL);
INSERT IGNORE INTO catalogue_items (id,sale_code,page_id,order_id,price,is_hidden,amount,definition_id,item_specialspriteid,name,description,is_package,package_name,package_description) VALUES ('2268','poster 22','24','38','3','0','1','251','22','Collection de papillons bleus','Magnifique reproduction de papillon','0',NULL,NULL);
INSERT IGNORE INTO catalogue_items (id,sale_code,page_id,order_id,price,is_hidden,amount,definition_id,item_specialspriteid,name,description,is_package,package_name,package_description) VALUES ('2269','poster 46','24','39','3','0','1','251','46','Petite étoile dorée','Scintille, scintille','0',NULL,NULL);
INSERT IGNORE INTO catalogue_items (id,sale_code,page_id,order_id,price,is_hidden,amount,definition_id,item_specialspriteid,name,description,is_package,package_name,package_description) VALUES ('2270','poster 47','24','40','3','0','1','251','47','Petite étoile argentée','Scintille, scintille','0',NULL,NULL);
INSERT IGNORE INTO catalogue_items (id,sale_code,page_id,order_id,price,is_hidden,amount,definition_id,item_specialspriteid,name,description,is_package,package_name,package_description) VALUES ('2271','poster 48','24','41','3','0','1','251','48','Grande étoile dorée','Tout ce qui brille...','0',NULL,NULL);
INSERT IGNORE INTO catalogue_items (id,sale_code,page_id,order_id,price,is_hidden,amount,definition_id,item_specialspriteid,name,description,is_package,package_name,package_description) VALUES ('2272','poster 49','24','42','3','0','1','251','49','Grande étoile argentée','Tout ce qui brille...','0',NULL,NULL);
INSERT IGNORE INTO catalogue_items (id,sale_code,page_id,order_id,price,is_hidden,amount,definition_id,item_specialspriteid,name,description,is_package,package_name,package_description) VALUES ('2273','poster 1006','24','43','3','0','1','251','1006','Poster de hibou','Ces yeux te suivent...','0',NULL,NULL);
INSERT IGNORE INTO catalogue_items (id,sale_code,page_id,order_id,price,is_hidden,amount,definition_id,item_specialspriteid,name,description,is_package,package_name,package_description) VALUES ('2274','poster 25','204','25','3','0','1','251','25','Poster de bonhomme de neige','Une nouvelle utilisation des carottes !','0',NULL,NULL);
INSERT IGNORE INTO catalogue_items (id,sale_code,page_id,order_id,price,is_hidden,amount,definition_id,item_specialspriteid,name,description,is_package,package_name,package_description) VALUES ('2275','poster 26','204','26','3','0','1','251','26','Poster d''ange','Regarde cette auréole briller !','0',NULL,NULL);
INSERT IGNORE INTO catalogue_items (id,sale_code,page_id,order_id,price,is_hidden,amount,definition_id,item_specialspriteid,name,description,is_package,package_name,package_description) VALUES ('2276','poster 27','204','27','3','0','1','251','27','Lot de houx','Décore les salles !','0',NULL,NULL);
INSERT IGNORE INTO catalogue_items (id,sale_code,page_id,order_id,price,is_hidden,amount,definition_id,item_specialspriteid,name,description,is_package,package_name,package_description) VALUES ('2277','poster 28','204','28','3','0','1','251','28','Lot de guirlandes argentées','10 guirlandes argentées','0',NULL,NULL);
INSERT IGNORE INTO catalogue_items (id,sale_code,page_id,order_id,price,is_hidden,amount,definition_id,item_specialspriteid,name,description,is_package,package_name,package_description) VALUES ('2278','poster 29','204','29','3','0','1','251','29','Lot de guirlandes dorées','10 guirlandes dorées','0',NULL,NULL);
INSERT IGNORE INTO catalogue_items (id,sale_code,page_id,order_id,price,is_hidden,amount,definition_id,item_specialspriteid,name,description,is_package,package_name,package_description) VALUES ('2279','poster 30','204','30','3','0','1','251','30','Gui','Fais une bise !','0',NULL,NULL);
INSERT IGNORE INTO catalogue_items (id,sale_code,page_id,order_id,price,is_hidden,amount,definition_id,item_specialspriteid,name,description,is_package,package_name,package_description) VALUES ('2280','poster 23','205','13','3','0','1','251','23','Poster de chauve-souris','Flap, flap, cri, cri...','0',NULL,NULL);
INSERT IGNORE INTO catalogue_items (id,sale_code,page_id,order_id,price,is_hidden,amount,definition_id,item_specialspriteid,name,description,is_package,package_name,package_description) VALUES ('2281','poster 42','205','14','3','0','1','251','42','Toile d''araignée','Mieux vaut éviter de lui rentrer dedans','0',NULL,NULL);
INSERT IGNORE INTO catalogue_items (id,sale_code,page_id,order_id,price,is_hidden,amount,definition_id,item_specialspriteid,name,description,is_package,package_name,package_description) VALUES ('2282','poster 43','205','15','3','0','1','251','43','Chaînes','Bouge, danse et déchaîne-toi !','0',NULL,NULL);
INSERT IGNORE INTO catalogue_items (id,sale_code,page_id,order_id,price,is_hidden,amount,definition_id,item_specialspriteid,name,description,is_package,package_name,package_description) VALUES ('2283','poster 45','205','16','3','0','1','251','45','Squelette','Il lui faut quelques Habburgers de plus','0',NULL,NULL);
INSERT IGNORE INTO catalogue_items (id,sale_code,page_id,order_id,price,is_hidden,amount,definition_id,item_specialspriteid,name,description,is_package,package_name,package_description) VALUES ('2284','poster 50','205','17','3','0','1','251','50','Poster de chauve-souris','Flap, flap, cri, cri...','0',NULL,NULL);
INSERT IGNORE INTO catalogue_items (id,sale_code,page_id,order_id,price,is_hidden,amount,definition_id,item_specialspriteid,name,description,is_package,package_name,package_description) VALUES ('2285','poster 2005','214','1','3','0','1','251','2005','Infobus','','0',NULL,NULL);
INSERT IGNORE INTO catalogue_items (id,sale_code,page_id,order_id,price,is_hidden,amount,definition_id,item_specialspriteid,name,description,is_package,package_name,package_description) VALUES ('2286','poster 2008','214','2','3','0','1','251','2008','Poster Habbo Cola','','0',NULL,NULL);
INSERT IGNORE INTO catalogue_items (id,sale_code,page_id,order_id,price,is_hidden,amount,definition_id,item_specialspriteid,name,description,is_package,package_name,package_description) VALUES ('2287','md_sofa','215','1','5','0','1','2267','0','Canapé Bubble Juice','Canapé de la gamme Bubble Juice.','0',NULL,NULL);

-- 4) Traductions FR des noms catalogue (posters déjà présents avant cette session)
UPDATE catalogue_items SET name='Plaque Poisson' WHERE definition_id=251 AND item_specialspriteid=3;
UPDATE catalogue_items SET name='Plaque Ours' WHERE definition_id=251 AND item_specialspriteid=4;
UPDATE catalogue_items SET name='Vitrine à marteau' WHERE definition_id=251 AND item_specialspriteid=7;
UPDATE catalogue_items SET name='Barreaux' WHERE definition_id=251 AND item_specialspriteid=16;
UPDATE catalogue_items SET name='Vitrine à papillons 1' WHERE definition_id=251 AND item_specialspriteid=17;
UPDATE catalogue_items SET name='Vitrine à papillons 2' WHERE definition_id=251 AND item_specialspriteid=18;
UPDATE catalogue_items SET name='Barreaux' WHERE definition_id=251 AND item_specialspriteid=20;
